version: '3'
services:
  eduwrench:
    image: wrenchproject/eduwrench:latest
    ports:
      - "${EDUWRENCH_GATSBY_PORT}:4000"
      - "${EDUWRENCH_NODE_PORT}:3000"
    volumes:
      - ${EDUWRENCH_DB_DIR}:/home/wrench/eduwrench/db
      - ${EDUWRENCH_SSL_CERTS_DIR}:/home/wrench/eduwrench/web/ssl
      - ${EDUWRENCH_SSL_CERTS_DIR}:/home/wrench/eduwrench/server/ssl
    environment:
      - EDUWRENCH_NODE_PORT=${EDUWRENCH_NODE_PORT}
      - EDUWRENCH_ENABLE_SSL=${EDUWRENCH_ENABLE_SSL}
      - EDUWRENCH_SSL_CERTIFICATE=${EDUWRENCH_SSL_CERTIFICATE}
      - EDUWRENCH_SSL_PRIVATE_KEY=${EDUWRENCH_SSL_PRIVATE_KEY}
