import React from "react"
import { Link } from "gatsby"

import Layout from "../components/layout"
import SEO from "../components/seo"
import Card from "react-bootstrap/Card"
import CardDeck from "react-bootstrap/CardDeck"
import "./privacypolicy.css"

const PrivacyPolicy = () => (
  <Layout>
    <SEO title="Privacy Policy" />
    <h3
      style={{
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        textAlign: "center",
        marginBottom: `30px`,
        marginTop: `50px`,
      }}
    >
      Privacy Policy
    </h3>
    <p style={{ backgroundColor: "#fefaec" }}>
      This Privacy Policy describes Our policies and procedures on the
      collection, use and disclosure of Your information when You use
      eduWRENCH.org and tells You about Your privacy rights and how the law
      protects You. We use Your Personal data to provide and improve
      eduWRENCH.org. By using eduWRENCH.org, You agree to the collection and use
      of information in accordance with this Privacy Policy.
    </p>
    <Card className="main">
      <Card.Body className="card">
        <div
          style={{ height: 50, backgroundColor: "#d3834a", borderRadius: 10 }}
        >
          <h6
            style={{
              marginTop: 15,
              color: "white",
              backgroundColor: "#d3834a",
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              textAlign: "center",
            }}
          >
            <a id="prerequisites">Interpretation and Definitions</a>
          </h6>
        </div>

        <h5 style={{ marginTop: 40, backgroundColor: "white" }}>
          Interpretation
        </h5>
        <p style={{ backgroundColor: "white", marginTop: 15 }}>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>

        <h5 style={{ marginTop: 25, backgroundColor: "white" }}>Definitions</h5>

        <p style={{ backgroundColor: "white", marginTop: 15 }}>
          For the purposes of this Privacy Policy:
        </p>

        <ul>
          <li>
            <b>You</b> means the individual accessing or using eduWRENCH.org.
          </li>
          <li>
            <b>eduWRENCH.org</b> (referred to as either “We”, “Us” or “Our” in
            this Agreement) refers to eduWRENCH.org project funded by the
            National Science Foundation under grants number{" "}
            <a
              target="_blank"
              rel="noreferrer"
              className="link"
              href="https://nsf.gov/awardsearch/showAward?AWD_ID=1923539"
            >
              1923539
            </a>
            , and{" "}
            <a
              target="_blank"
              rel="noreferrer"
              className="link"
              href="https://nsf.gov/awardsearch/showAward?AWD_ID=1923621"
            >
              1923621
            </a>
            .
          </li>
          <li>
            <b>Account</b> means a unique account created for You to access our
            eduWRENCH.org or parts of eduWRENCH.org.
          </li>
          <li>
            <b>Country</b> refers to: United States
          </li>
          <li>
            <b>Third-party Social Media Service</b> refers to any website or any
            social network website through which a User can log in or create an
            account to use eduWRENCH.org.
          </li>
          <li>
            <b>Personal Data</b> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <b>Cookies</b> are small files that are placed on Your computer,
            mobile device or any other device by a website, containing the
            details of Your browsing history on that website among its many
            uses.
          </li>
          <li>
            <b>Usage Data</b> refers to data collected automatically, either
            generated by the use of eduWRENCH.org or from eduWRENCH.org
            infrastructure itself (for example, the duration of a page visit).
          </li>
        </ul>
        <hr></hr>
        <div
          style={{ height: 50, backgroundColor: "#d3834a", borderRadius: 10 }}
        >
          <h6
            style={{
              marginTop: 15,
              color: "white",
              backgroundColor: "#d3834a",
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              textAlign: "center",
            }}
          >
            <a id="objectives">Collecting and Using Your Personal Data</a>
          </h6>
        </div>
        <h5 style={{ marginTop: 40, backgroundColor: "white" }}>
          Personal Data
        </h5>
        <p className="privacy">
          While using eduWRENCH.org, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </p>

        <ul>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        <h5 style={{ marginTop: 5, backgroundColor: "white" }}>Usage Data</h5>

        <p className="privacy">
          Usage Data is collected automatically when using eduWRENCH.org. Usage
          Data may include information such as Your Device’s Internet Protocol
          address (e.g. IP address), browser type, browser version, the pages of
          eduWRENCH.org that You visit, the time and date of Your visit, the
          time spent on those pages, unique device identifiers and other
          diagnostic data. When You access eduWRENCH.org by or through a mobile
          device, We may collect certain information automatically, including,
          but not limited to, the type of mobile device You use, Your mobile
          device unique ID, the IP address of Your mobile device, Your mobile
          operating system, the type of mobile Internet browser You use, unique
          device identifiers and other diagnostic data. We may also collect
          information that Your browser sends whenever You visit eduWRENCH.org
          or when You access eduWRENCH.org by or through a mobile device.
        </p>

        <h5 style={{ marginTop: 5, backgroundColor: "white" }}>
          Tracking Technologies and Cookies
        </h5>

        <p className="privacy">
          We use Cookies and similar tracking technologies to track the activity
          on eduWRENCH.org and store certain information. Tracking technologies
          used are beacons, tags, and scripts to collect and track information
          and to improve and analyze eduWRENCH.org. You can instruct Your
          browser to refuse all Cookies or to indicate when a Cookie is being
          sent. However, if You do not accept Cookies, You may not be able to
          use some parts of eduWRENCH.org. Cookies can be “Persistent” or
          “Session” Cookies. Persistent Cookies remain on your personal computer
          or mobile device when You go offline, while Session Cookies are
          deleted as soon as You close your web browser. We use both session and
          persistent Cookies for the purposes set out below:
        </p>

        <ul>
          <li>
            <b>Functionality Cookies</b>
          </li>
          <ul>
            <li>Type: Persistent Cookies</li>
            <li>Administered by: Us</li>
            <li>
              Purpose: These Cookies allow us to remember choices You make when
              You use eduWRENCH.org, such as remembering your login details or
              language preference. The purpose of these Cookies is to provide
              You with a more personal experience and to avoid You having to
              re-enter your preferences every time You use eduWRENCH.org.
            </li>
          </ul>
        </ul>

        <h5 style={{ marginTop: 5, backgroundColor: "white" }}>
          Use of Your Personal Data
        </h5>
        <p className="privacy">
          eduWRENCH.org may use Personal Data for the following purposes:
        </p>
        <ul>
          <li>
            <b>To provide and maintain eduWRENCH.org</b>, including to monitor
            the usage of eduWRENCH.org.
          </li>
          <li>
            <b>To manage Your Account</b>: to manage Your registration as a user
            of eduWRENCH.org. The Personal Data You provide can give You access
            to different functionalities of eduWRENCH.org that are available to
            You as a registered user.
          </li>
          <li>
            <b>To contact You</b>: To contact You by email or other equivalent
            forms of electronic communication, such as a mobile application’s
            push notifications regarding updates or informative communications
            related to the functionalities and new capabilities.
          </li>
          <li>
            <b>To provide You</b> with news and general information about other
            new capabilities and events unless You have opted not to receive
            such information.
          </li>
          <li>
            <b>To manage Your requests</b>: To attend and manage Your requests
            to Us.
          </li>
        </ul>

        <p className="privacy">
          We may share your personal information in the following situations:
        </p>
        <ul>
          <li>
            <b>With NSF</b>: We may share Your information with the National
            Science Foundation.
          </li>
          <li>
            <b>Research Publications</b>: We may share anonymized information on
            research publications. No personal information will be shared in
            research publications, only aggregated information.
          </li>
        </ul>

        <h5 style={{ marginTop: 5, backgroundColor: "white" }}>
          Retention of Your Personal Data
        </h5>
        <p className="privacy">
          eduWRENCH.org will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use Your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes, and
          enforce our legal agreements and policies. eduWRENCH.org will also
          retain Usage Data for internal analysis purposes. Usage Data is
          generally retained for a shorter period of time, except when this data
          is used to strengthen the security or to improve the functionality of
          eduWRENCH.org, or We are legally obligated to retain this data for
          longer time periods.
        </p>

        <h5 style={{ marginTop: 5, backgroundColor: "white" }}>
          Transfer of Your Personal Data
        </h5>
        <p className="privacy">
          Your information, including Personal Data, is processed at the
          University of Southern California and University of Hawaii research
          facilities and in any other places where the parties involved in the
          processing are located. It means that this information may be
          transferred to — and maintained on — computers located outside of Your
          state, province, country or other governmental jurisdiction where the
          data protection laws may differ than those from Your jurisdiction.
          Your consent to this Privacy Policy followed by Your submission of
          such information represents Your agreement to that transfer.
          eduWRENCH.org will take all steps reasonably necessary to ensure that
          Your data is treated securely and in accordance with this Privacy
          Policy and no transfer of Your Personal Data will take place to an
          organization or a country unless there are adequate controls in place
          including the security of Your data and other personal information.
        </p>
        <hr></hr>

        <h5 style={{ marginTop: 5, backgroundColor: "white" }}>
          Disclosure of Your Personal Data
        </h5>

        <ul>
          <li>
            <b>Law enforcement</b>: Under certain circumstances, eduWRENCH.org
            may be required to disclose Your Personal Data if required to do so
            by law or in response to valid requests by public authorities (e.g.
            a court or a government agency).
          </li>
          <li>
            <b>Other legal requirements</b>: eduWRENCH.org may disclose Your
            Personal Data in the good faith belief that such action is necessary
            to:
          </li>
          <ul>
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of eduWRENCH.org</li>
            <li>
              Prevent or investigate possible wrongdoing in connection with
              eduWRENCH.org
            </li>
            <li>
              Protect the personal safety of Users of eduWRENCH.org or the
              public
            </li>
            <li>Protect against legal liability</li>
          </ul>
        </ul>

        <h5 style={{ marginTop: 5, backgroundColor: "white" }}>
          Security of Your Personal Data
        </h5>
        <p className="privacy">
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect Your Personal Data, We cannot guarantee
          its absolute security.
        </p>

        <hr></hr>

        <div
          style={{ height: 50, backgroundColor: "#d3834a", borderRadius: 10 }}
        >
          <h6
            style={{
              marginTop: 15,
              color: "white",
              backgroundColor: "#d3834a",
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              textAlign: "center",
            }}
          >
            <a id="objectives">Children’s Privacy</a>
          </h6>
        </div>

        <p className="privacy">
          eduWRENCH.org does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If You are a parent or guardian and You are aware
          that Your child has provided Us with Personal Data, please contact Us.
          If We become aware that We have collected Personal Data from anyone
          under the age of 13 without verification of parental consent, We will
          take steps to remove that information from Our servers. We also may
          limit how We collect, use, and store some of the information of Users
          between 13 and 18 years old. In some cases, this means We will be
          unable to provide certain functionality of eduWRENCH.org to these
          users. If We need to rely on consent as a legal basis for processing
          Your information and Your country requires consent from a parent, We
          may require Your parent’s consent before We collect and use that
          information.
        </p>

        <hr></hr>

        <div
          style={{ height: 50, backgroundColor: "#d3834a", borderRadius: 10 }}
        >
          <h6
            style={{
              marginTop: 15,
              color: "white",
              backgroundColor: "#d3834a",
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              textAlign: "center",
            }}
          >
            <a id="objectives">Links to Other Websites</a>
          </h6>
        </div>

        <p className="privacy">
          eduWRENCH.org may contain links to other websites that are not
          operated by Us. If You click on a third party link, You will be
          directed to that third party’s site. We strongly advise You to review
          the Privacy Policy of every site You visit. We have no control over
          and assume no responsibility for the content, privacy policies or
          practices of any third party sites or services.
        </p>
        <hr></hr>
        <div
          style={{ height: 50, backgroundColor: "#d3834a", borderRadius: 10 }}
        >
          <h6
            style={{
              marginTop: 15,
              color: "white",
              backgroundColor: "#d3834a",
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              textAlign: "center",
            }}
          >
            <a id="objectives">Changes to this Privacy Policy</a>
          </h6>
        </div>

        <p className="privacy">
          We may update our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page. We will
          let You know via email and/or a prominent notice on eduWRENCH.org,
          prior to the change becoming effective and update the “Last updated”
          date at the bottom of this Privacy Policy. You are advised to review
          this Privacy Policy periodically for any changes. Changes to this
          Privacy Policy are effective when they are posted on this page.
        </p>

        <h5 style={{ marginTop: 5, backgroundColor: "white" }}>Contact Us</h5>
        <p className="privacy">
          If you have any questions about this Privacy Policy, You can contact
          us:
        </p>
        <ul>
          <li>
            By email:{" "}
            <a
              href="mailto:support@wrench-project.org"
              style={{ color: "#d3834a", backgroundColor: "white" }}
            >
              support@wrench-project.org
            </a>{" "}
          </li>
        </ul>

        <p className="privacy">Last updated: March 19, 2020</p>
      </Card.Body>
    </Card>
  </Layout>
)

export default PrivacyPolicy
